<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <UserSecretsId>84723b4b-c07e-4916-9809-245e2fd55245</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserService.Application\UserService.Application.csproj" />
    <ProjectReference Include="..\UserService.Domain\UserService.Domain.csproj" />
    <ProjectReference Include="..\UserService.Infrastructure\UserService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
